<template>
	<section class="mx-4 sm:mx-8 lg:w-1/2" :class="{ 'lg:mr-0': postId }">
		<!-- New Comment Component (incase of new comment)-->
		<NewCommentComponent v-if="postId" @updateComments="$emit('updateComments')" :post-id="postId" />
		<!-- Comment structure (rendered from the comments array) -->
		<div v-for="(comment, key) in comments" :key="key" class="flex flex-col gap-y-8 my-4">
			<!-- Comment -->
			<CommentComponent :id="comment.commentId" @updateComments="$emit('updateComments')" :comment="comment" />
		</div>
	</section>
</template>

<script>
import CommentComponent from '../components/comments/CommentComponent.vue'
import NewCommentComponent from '@/components/comments/NewCommentComponent.vue'

export default {
	name: 'CommentLayout',

	components: {
		CommentComponent,
		NewCommentComponent,
	},

	//Props the list of comments which the comment components are generated by
	props: {
		comments: Array,
		postId: String,
	},
}
</script>
